### ISSUE TITLE
AD-Vi'sの改造

### ISSUE THREAD

**Issue by jms-fukuta** [jms-web/ANDEN#19]
タッチPC用のプログラムにて本社の保全担当の入退出を管理する
プログラム名はDejidon.exe
納期は７月末とする
見積作成する

7月末ではテストが不十分なので、アンデン殿に協力してもらい調整する

**Comment by jms-fukuta** [comment]
PG処理概要に関しては
Z:\ANDEN201805CD\Dejidonの処理概要.xlsx
に保存

**Comment by jms-funato** [comment]
AD-Vi'sのプロジェクトはAD-VISリポジトリで管理している
